version: '3.8'

services:
  stock-prediction:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      # オプション: ログやキャッシュを永続化したい場合
      - ./logs:/app/logs
    restart: unless-stopped
    container_name: stock-prediction-app